# Generated by Django 4.2.4 on 2023-08-19 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='d_slug',
            field=models.SlugField(default='department'),
            preserve_default=False,
        ),
    ]
