# Generated by Django 4.2.4 on 2023-08-19 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schoolApp', '0002_department_d_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseName', models.CharField(max_length=50)),
                ('depF', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schoolApp.department')),
            ],
        ),
    ]
